services:
  # Auth Service Database
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5433:5432"  # External 5433 → Internal 5432
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  # Redis for caching/sessions
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # RabbitMQ for messaging
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # App communication
      - "15672:15672"   # Management UI
    networks:
      - backend

  # Config server
  config-server:
    image: ecommerce-config-server:latest
    container_name: config-server
    build:
      context: ../ecommerce-config-server
    ports:
      - "8888:8888"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  auth-postgres-data:

networks:
  backend:
    driver: bridge